# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Xmazon' do
pod "GROAuth2SessionManager" , "~> 0.2"
end

target 'XmazonTests' do
pod "GROAuth2SessionManager" , "~> 0.2"

end

target 'XmazonUITests' do

end

